spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
     url: jdbc:h2:mem:intervals;TRACE_LEVEL_FILE=4
     driverClassName: org.h2.Driver
     username: root
     password: root
  h2:
    console:
      enabled: true
      path: /h2-console